### ISSUE TITLE
Are the quadrupoles you use traceless or not?

### ISSUE THREAD

**Issue by 20171130** [rinikerlab/EquivariantMultipoleGNN#1]
I have downloaded the data you provided and found that the quadrupoles typically have a none zero trace which is much larger than the elements off diagonal. However, the outer products in your code are traceless, as in eq 17. in your paper. Are the quadrupole prediction results in your paper about traceless quadrupoles, or quadrupoles with trace?

**Comment by 20171130** [comment]
I also want to know how the MAE is computed. Is it the sum or the average of per component error, or the square root of L2 norm?

**Comment by moritztdev** [comment]
Hey

I assume you mean the dataset on the ETH research collection? The quadrupoles in this dataset are reported in the same way as given by PSI4 which are not necessarily traceless. 
For the training, the quadrupoles were first detraced and in the paper we refer to these traceless quadrupoles.
Also, as you noted, the model returns traceless quadrupoles.

Errors are computed per component, i.e. element-wise subtraction/square.
