### ISSUE TITLE
Training scripts

### ISSUE THREAD

**Issue by jthorton** [rinikerlab/EquivariantMultipoleGNN#2]
Hi fantastic work and thanks for sharing the model and weights this is really helpful, I was wondering if it would also be possible to share some training scripts as I would love to be able to train my own version of this model to data computed with a different level of theory?

**Comment by moritztdev** [comment]
Thanks for your interest. I’ve added a notebook (example_training.ipynb) which shows how we prepared the data and the functions used to train the model, hope it helps.

Depending on your dataset you may also be able to load all graphs with numpy or so but for larger datasets  I would recommend to use tfrecords (as in the example notebook).
