### ISSUE TITLE
How to train a new model?

### ISSUE THREAD

**Issue by Liaokang123456** [rinikerlab/EquivariantMultipoleGNN#3]
The data is "data.hdf5"

**Comment by moritztdev** [comment]
Yes, the is a description of the data structure in the README.md.

**Comment by Liaokang123456** [comment]
Sorry for disturbing you with this letter.
&nbsp; &nbsp; I am a student from NanJing University, i would appreciate it greatly if you give one script which train an new model; i just want to test some other data by using your method.


廖二饼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rinikerlab/EquivariantMultipoleGNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rinikerlab/EquivariantMultipoleGNN] How to train a new model? (Issue #3)





 
Yes, the is a description of the data structure in the README.md.

**Comment by moritztdev** [comment]
Hi

There is a notebook ('example_training.ipynb') which shows you how to prepare data/train the model.

Hope that helps.

**Comment by Liaokang123456** [comment]
I don't know how to prepare the data for the model.

In the notebook,

"for graphs, monopoles, dipoles, quadrupoles in data*"

if i use the "data.hdf5", how to define the data*?

**Comment by Liaokang123456** [comment]
How to save the trained model?
Add load_model() function after "#Training Loop"?
